Fix #1 criar splash screen
OrcestraGamificacao/portalOrcApp pull request #24
Opened 2019-10-30 15:42 UTC by emysdias

# Pull Request Template

### #1 criar splash screen

### Conteúdo do Pull Request

O conteúdo do pull request deve ser constituído de uma lista contendo as principais modificações feitas.

```
Nesse pull request foi feito:

História #25
Issue #1 
Correção de bugs
```

Adicionar o pipeline, os revisores, que serão integrantes de EPS, e as labels se for necessário.

### Condição

Para ser aceito sem grandes mudanças, o pull request deve estar de acordo com o guia de contribuição do repositório.

2019-10-30 19:32 UTC, alan-ms requested changes
## Rewiew
A slash screen está bugada. 
Rodando o aplicativo no celular é apresentado a seguinte tela da imagem abaixo.
![Screenshot from 2019-10-30 16-27-48](https://user-images.githubusercontent.com/35638067/67892105-c1cec180-fb32-11e9-969c-c5b9c19b320e.png)

2019-11-04 17:00 UTC, lucianaribeiro requested changes
Mudanças:

- Vocês renderizaram a splash screen direto no routes e não é assim que deve ser feito:
   1. Vocês vão criar a classe App dentro da routes.js e la vocês vão chamar a splash screen
- O arquivo splashScreen deve começar com letra maiúscula. 
- A tela não esta responsiva:
  1. A imagem não cobre toda a tela, é possível ver na margem esquerda que está branca
  2. Depois que a imagem cresce ela trava e não vai pra tela inicial do app, e na verdade ela é so um efeito que deve ser mostrado e logo em seguida renderizado para a tela inicial. 
  3. Segue em anexo a foto de como ficou no IOS

 <img src="https://user-images.githubusercontent.com/23436276/68140246-42623900-ff0a-11e9-92aa-9b67f84464e5.jpg" width="260" height="">

2019-11-09 23:18 UTC, emysdias commented
blob:https://web.telegram.org/7bce911c-e197-4f5e-8345-2ada9acbf1d2

Agora sim está funcionando e está de acordo com o protótipo

2019-11-09 23:20 UTC, emysdias commented
> <img alt="" width="260" height="" src="https://user-images.githubusercontent.com/52640974/68536222-3b825e80-032e-11ea-98ad-181e40f8f299.jpeg">

Agora sim está finalizado e de acordo com o protótipo

2019-11-09 23:36 UTC, alan-ms approved these changes

2019-11-13 16:49 UTC, closed without merging