Fix #12 criar a barra de navegação inferior
OrcestraGamificacao/portalOrcApp pull request #25
Opened 2019-11-04 21:18 UTC by adrielelopes

# Pull Request Template

### Criar a barra de navegação inferior
```
Fix #12 criar a barra de navegação inferior
```
### Conteúdo do Pull Request

```
Nesse pull request foi feito:
Criação da barra de navegação inferior para as páginas de "Início", "Membros" e "Atividades".
Inclusão das rotas (comentadas) para as páginas do "Perfil" e "Tarefas"

História #25
Issue #12
Correção de bugs
```

2019-11-07 01:34 UTC, alan-ms requested changes
Os headers da tela de membros e atividades não estão com a formatação igual quando foram aceitas os PR's das respectivas issues.

![photo5051114894715365510](https://user-images.githubusercontent.com/35638067/68352510-6d54b480-00e5-11ea-99d5-941c8d85ce01.jpg)

2019-11-08 02:42 UTC, vitorAlves7 commented
Conseguimos formatar as telas de membros e atividades

![image](https://user-images.githubusercontent.com/43835325/68445263-2c79a000-01b8-11ea-9294-7d14f137f25f.png)

2019-11-08 02:46 UTC, adrielelopes commented
Aqui de atividades ![photo5055382069277993171](https://user-images.githubusercontent.com/54216852/68445429-ac076f00-01b8-11ea-8616-e0e0f2722dbf.jpg)

2019-11-08 13:25 UTC, alan-ms approved these changes

2019-11-13 00:44 UTC, merged